#:schema node_modules/wrangler/config-schema.json
name = "api-nodejs-hello-world"
main = ".worker-next/index.mjs"
assets = ".worker-next/assets"
compatibility_date = "2024-07-01"
compatibility_flags = ["experimental:nodejs_compat_v2"]
workers_dev = true
minify = false                                          # let's disable minification for easier debuggability

# The aliases below should not be needed (we don't want users to have to define the aliases themselves)
[alias]
# critters is `require`d from `pages.runtime.prod.js` when running wrangler dev, so we need to stub it out
"critters" = "../../nextjs-worker-builder/src/build/build-worker/templates/shims/empty.ts"
# @opentelemetry/api is `require`d when running wrangler dev, so we need to stub it out
# IMPORTANT: we shim @opentelemetry/api to the throwing shim so that it will throw right away, this is so that we throw inside the 
#            try block here: https://github.com/vercel/next.js/blob/9e8266a7/packages/next/src/server/lib/trace/tracer.ts#L27-L31
#            causing the code to require the 'next/dist/compiled/@opentelemetry/api' module instead (which properly works)
"@opentelemetry/api" = "../../nextjs-worker-builder/src/build/build-worker/templates/shims/throw.ts"
